### ISSUE TITLE
run with error

### ISSUE THREAD

**Issue by angeluau** [StevenWD/DRGD#3]
wsy@user1-R730:~/tae/DRGD-master$ python main.py -t
Using TensorFlow backend.
Traceback (most recent call last):
  File "main.py", line 30, in <module>
    train(source_helper, target_input_helper, target_output_helper, valid_source_helper, valid_target_output_helper, char_dict)
  File "/home/wsy/tae/DRGD-master/run.py", line 16, in train
    model.build()
  File "/home/wsy/tae/DRGD-master/model.py", line 23, in build
    self.encoder = Encoder()
  File "/home/wsy/tae/DRGD-master/encoder.py", line 13, in __init__
    self.cell_fw = self.build_cell(self.config['cell_classname'], 'cell_fw')
  File "/home/wsy/tae/DRGD-master/encoder.py", line 39, in build_cell
    **self.config['cell']['cell_params'])
TypeError: __init__() got an unexpected keyword argument 'name'

**Comment by wangshuo6699** [comment]
我也遇到这个问题了，你解决了吗

**Comment by StevenWD** [comment]
Sorry for getting back so late. The environment should be tensorflow 1.12 + python3.6. The code should work well under such an environment.
